# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
set_msg_config -id {Synth 8-256} -limit 10000
set_msg_config -id {Synth 8-638} -limit 10000
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir W:/Desktop/PmodENC_Source/project_test_pmodenc/project_test_pmodenc.cache/wt [current_project]
set_property parent.project_path W:/Desktop/PmodENC_Source/project_test_pmodenc/project_test_pmodenc.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part digilentinc.com:nexys4_ddr:part0:1.1 [current_project]
set_property ip_output_repo w:/Desktop/PmodENC_Source/project_test_pmodenc/project_test_pmodenc.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib {
  W:/Desktop/PmodENC_Source/Encoder.v
  W:/Desktop/PmodENC_Source/Debouncer.v
  W:/Desktop/PmodENC_Source/PmodENC.v
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc //ugradfs.doe.carleton.ca/mahtabmohammed/win/Desktop/PmodENC_Source/Nexys4DDR_Master.xdc
set_property used_in_implementation false [get_files //ugradfs.doe.carleton.ca/mahtabmohammed/win/Desktop/PmodENC_Source/Nexys4DDR_Master.xdc]


synth_design -top PmodENC -part xc7a100tcsg324-1


write_checkpoint -force -noxdef PmodENC.dcp

catch { report_utilization -file PmodENC_utilization_synth.rpt -pb PmodENC_utilization_synth.pb }
